### PR TITLE
1.19.70

### PR DESCRIPTION
**Pull request by Kas-tle**

### CODE REVIEW

**Comment by Kazzuk** [comment]
Hello thanks for the contribution but this PR doesn’t quite suffice for the 1.19.70 (575) update as it requires the [protocol](https://github.com/CloudburstMC/Protocol/tree/develop) lib to be updated. I’ll have a look at updating ProxyPass later this week, there’s a couple things to fix with data dumping as well.

**Comment by Kas-tle** [comment]
Alrighty, thanks! Personally it compiled and worked fine for me by just bumping the version. Perhaps it may be because I pinned the protocol version to `2.9.17-20230217.002312-1` (same version Geyser currently uses). I didn't run into any obvious issues but thanks for looking into some of the minor issues with the data.

**Comment by Kazzuk** [comment]
It’ll join fine but it won’t encode/decode new packets that were introduced in `1.19.70` and will have issues with any new changes in current packets. Though just to add on about `1.19.70` support, supreme is working on finishing the new `protocol-v3` branch (supports `1.19.70`) of the protocol lib [here](https://github.com/CloudburstMC/ProxyPass/tree/protocol-v3).

**Comment by Kas-tle** [comment]
Ah I see that makes sense. I think Geyser so far has just ignored anything beyond what was required to function with 1.19.70 clients for now. So this will work for my purposes in the meantime. Thanks for clarifying!

**Pull request closed without merging**
